version: "3"
services:
  db:
    image: postgres:15.15-trixie
    container_name: exercises-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=exercises
    networks:
      - exercises-network
    volumes:
      - pg_exercises:/var/lib/postgresql

networks:
  exercises-network:
    driver: bridge

volumes:
  pg_exercises: